name: TwitchMode
version: '${version}'
main: uwu.vutuvmonke.twitchmode.TwitchMode
api-version: '1.20'
load: STARTUP
authors: [ MonkeDevs ]

commands:
  stream:
    permission: 'monketwitchmode.stream'
  monketwitchmode:
    permission: 'monketwitchmode.reload'
    aliases: [ mtm, twitch ]

permissions:
  monketwitchmode.stream:
    default: true
  monketwitchmode.reload:
    default: op
  monketwitchmode.*:
    default: op
    children:
      - monketwitchmode.stream
      - monketwitchmode.reload